:white_check_mark: Fix the failed tests caused by the changes in the Wikipedia articles (#124)
* :white_check_mark: Fix the failed tests caused by the changes in the Wikipedia articles

* Fix the AttributeError: 'dict' object has no attribute 'response' in test_api_wikipedia